server:
  port: 8072

spring:
  application:
    name: practiceapi
 # session:
  #  store-type: jdbc
   # jdbc:
    #  initialize-schema: always
  h2:
    console:
      enable: true;
      path: /h2-console

datasource:
  url: jdbc:h2:mem:test
  username: sa
  password:
  driver-class-name: org.h2.Driver
#  datasource:
 #   url: jdbc:mariadb://localhost:3306/myoci
  #  username: test
   # password: 1234
    #driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#resilience4j.ratelimeter
resilience4j.ratelimiter:
  instances:
    backendA:
      limitForPeriod: 1
      limitRefreshPeriod: 30s
      timeoutDuration: 0






myblog:
  strKey: "qwerasdKDJFIEONqweriahsdfjasjdERRERqsfhgkop"
  myEmail: "tahyo27@gmail.com"

