spring:
  application:
    name: practiceapi
  h2:
    console:
      enable: true;
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8072

myblog:
  jwtStrkey: "qwerasdKDJFIEONqweriahsdfjasjdERRERqsfhgkop"
  adminEmail: "tahyo27@gmail.com"

